"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var tenantControllers_1 = require("../controllers/tenantControllers");
var router = express_1.default.Router();
router.get("/:cognitoId", tenantControllers_1.getTenant);
router.put("/:cognitoId", tenantControllers_1.updateTenant);
router.post("/", tenantControllers_1.createTenant);
router.get("/:cognitoId/current-residences", tenantControllers_1.getCurrentResidences);
router.post("/:cognitoId/favorites/:propertyId", tenantControllers_1.addFavoriteProperty);
router.delete("/:cognitoId/favorites/:propertyId", tenantControllers_1.removeFavoriteProperty);
exports.default = router;
